### ISSUE TITLE
DB connection issue shut down Delayed_Job for 2 days

### ISSUE THREAD

**Issue by MichaelA59** [collectiveidea/delayed_job#1016]
I have no clue what caused this but the issue was fixed by re-deploying the previous instance of our backend. As soon as we did that, all the emails that weren't sent for the past 2 days all came through at once. 

I am thinking it had something to do with a DB connection issue whereby Postgres disconnected somehow. I don't really understand how this all works though and could really use furth clarification.

The relevant logs we found are below:

```
F, [2018-01-21T11:07:10.409578 #19288] FATAL -- : 
PG::UnableToSend (SSL SYSCALL error: EOF detected
):
```

```
F, [2018-01-21T10:13:10.254502 #19374] FATAL -- : PG::UnableToSend: socket not open
: UPDATE "delayed_jobs" SET "locked_by" = NULL, "locked_at" = NULL WHERE "delayed_jobs"."locked_by" = $1
```

**Comment by albus522** [comment]
After that error, DJ exited as it didn't know how to recover. I am guessing you didn't have a process monitor making sure there was an active worker process such as monit or god.

**Comment by MichaelA59** [comment]
I'm sorry could you possibly explain that a little more simply?

**Comment by albus522** [comment]
There are any number of issues that can come up that delayed job cannot recover from at which point DJ will exit. The issue you posted above is one of those issues. It is the job of a process monitoring tool, such as monit, god, or others, to watch and make sure the processes you want to keep running stay running and restart them in the event they crash. DJ does not do this monitoring for you.

**Comment by schainker** [comment]
We also just encountered a similar issue.  A MySQL bug resulted in an unexpected restart of MySQL.  

Since the lock was already set on the job, DJ did nothing upon restart, and the job state showed no errors or failed attempts. 

When DJ is exiting, would it be "safe" to remove locks on jobs in these situations? This way, when DJ comes back up, it will at least know what is "safe" to pick up again.

**Comment by albus522** [comment]
@schainker When DJ can't get a DB connection, it can't unlock the job. Locks do automatically timeout after the max run time. Also, I believe we try to reconnect to the DB a number of times, so as long as the DB is only gone for a short period, the process will cleanly continue.

**Comment by schainker** [comment]
Our DB disappeared for 20 seconds, which is probably too long for this to work.  However, how does a lock "timeout" if DJ exists and comes back?

**Comment by albus522** [comment]
After max_run_time has passed since the job was locked, it is no longer considered locked. It is almost a failsafe catch, however occasionally it leads to double execution as there are some edge cases which can bypass ruby's timeout.

**Comment by NOX73** [comment]
I have the similar issue. After some deployments (it happens from time to time) it fails to connect to the DB and after DB recovery worker refuses to consume jobs even if there are in the queue. Only restart helps to start processing jobs. Here is the full log:

```
2018-05-29T09:12:28+0000: [Worker(delayed_job host:2021426028b3 pid:1)] Starting job worker
D, [2018-05-29T09:12:28.914094 #1] DEBUG -- : Delayed::Backend::ActiveRecord::Job Load (2.4ms)UPDATE "delayed_jobs" SET locked_at = '2018-05-29 09:12:28.907062', locked_by = 'delayed_job host:2021426028b3 pid:1' WHERE id IN (SELECT "delayed_jobs"."id" FROM "delayed_jobs" WHERE ((run_at <= '2018-05-29 09:12:28.862951' AND (locked_at IS NULL OR locked_at < '2018-05-29 05:12:28.862989') OR locked_by = 'delayed_job host:2021426028b3 pid:1') AND failed_at IS NULL) ORDER BY priority ASC, run_at ASC LIMIT 1 FOR UPDATE) RETURNING *
D, [2018-05-29T09:12:33.916386 #1] DEBUG -- : Delayed::Backend::ActiveRecord::Job Load (0.4ms)UPDATE "delayed_jobs" SET locked_at = '2018-05-29 09:12:33.915438', locked_by = 'delayed_job host:2021426028b3 pid:1' WHERE id IN (SELECT "delayed_jobs"."id" FROM "delayed_jobs" WHERE ((run_at <= '2018-05-29 09:12:33.914925' AND (locked_at IS NULL OR locked_at < '2018-05-29 05:12:33.914972') OR locked_by = 'delayed_job host:2021426028b3 pid:1') AND failed_at IS NULL) ORDER BY priority ASC, run_at ASC LIMIT 1 FOR UPDATE) RETURNING *
2018-05-29T09:12:33+0000: [Worker(delayed_job host:2021426028b3 pid:1)] Error while reserving job: PG::ConnectionBad: PQconsumeInput() could not receive data from server: Socket operation on non-socket
: UPDATE "delayed_jobs" SET locked_at = '2018-05-29 09:12:33.915438', locked_by = 'delayed_job host:2021426028b3 pid:1' WHERE id IN (SELECT "delayed_jobs"."id" FROM "delayed_jobs" WHERE ((run_at <= '2018-05-29 09:12:33.914925' AND (locked_at IS NULL OR locked_at < '2018-05-29 05:12:33.914972') OR locked_by = 'delayed_job host:2021426028b3 pid:1') AND failed_at IS NULL) ORDER BY priority ASC, run_at ASC LIMIT 1 FOR UPDATE) RETURNING *

//..........................................................

: UPDATE "delayed_jobs" SET locked_at = '2018-05-29 09:13:13.930017', locked_by = 'delayed_job host:2021426028b3 pid:1' WHERE id IN (SELECT "delayed_jobs"."id" FROM "delayed_jobs" WHERE ((run_at <= '2018-05-29 09:13:13.929609' AND (locked_at IS NULL OR locked_at < '2018-05-29 05:13:13.929654') OR locked_by = 'delayed_job host:2021426028b3 pid:1') AND failed_at IS NULL) ORDER BY priority ASC, run_at ASC LIMIT 1 FOR UPDATE) RETURNING *
D, [2018-05-29T09:13:18.932458 #1] DEBUG -- : Delayed::Backend::ActiveRecord::Job Load (0.3ms)UPDATE "delayed_jobs" SET locked_at = '2018-05-29 09:13:18.931697', locked_by = 'delayed_job host:2021426028b3 pid:1' WHERE id IN (SELECT "delayed_jobs"."id" FROM "delayed_jobs" WHERE ((run_at <= '2018-05-29 09:13:18.931292' AND (locked_at IS NULL OR locked_at < '2018-05-29 05:13:18.931338') OR locked_by = 'delayed_job host:2021426028b3 pid:1') AND failed_at IS NULL) ORDER BY priority ASC, run_at ASC LIMIT 1 FOR UPDATE) RETURNING *
2018-05-29T09:13:18+0000: [Worker(delayed_job host:2021426028b3 pid:1)] Error while reserving job: PG::ConnectionBad: PQconsumeInput() could not receive data from server: Socket operation on non-socket
: UPDATE "delayed_jobs" SET locked_at = '2018-05-29 09:13:18.931697', locked_by = 'delayed_job host:2021426028b3 pid:1' WHERE id IN (SELECT "delayed_jobs"."id" FROM "delayed_jobs" WHERE ((run_at <= '2018-05-29 09:13:18.931292' AND (locked_at IS NULL OR locked_at < '2018-05-29 05:13:18.931338') OR locked_by = 'delayed_job host:2021426028b3 pid:1') AND failed_at IS NULL) ORDER BY priority ASC, run_at ASC LIMIT 1 FOR UPDATE) RETURNING *
PG::ConnectionBad: PQconsumeInput() could not receive data from server: Socket operation on non-socket
: SELECT c.relname FROM pg_class c LEFT JOIN pg_namespace n ON n.oid = c.relnamespace WHERE n.nspname = ANY (current_schemas(false)) AND c.relkind IN ('r','v','m','f')
/usr/local/bundle/gems/activerecord-5.2.0.rc1/lib/active_record/connection_adapters/postgresql/database_statements.rb:63:in `async_exec'
/usr/local/bundle/gems/activerecord-5.2.0.rc1/lib/active_record/connection_adapters/postgresql/database_statements.rb:63:in `block (2 levels) in query'
/usr/local/bundle/gems/activesupport-5.2.0.rc1/lib/active_support/dependencies/interlock.rb:48:in `block in permit_concurrent_loads'
/usr/local/bundle/gems/activesupport-5.2.0.rc1/lib/active_support/concurrency/share_lock.rb:187:in `yield_shares'
/usr/local/bundle/gems/activesupport-5.2.0.rc1/lib/active_support/dependencies/interlock.rb:47:in `permit_concurrent_loads'
/usr/local/bundle/gems/activerecord-5.2.0.rc1/lib/active_record/connection_adapters/postgresql/database_statements.rb:62:in `block in query'
/usr/local/bundle/gems/activerecord-5.2.0.rc1/lib/active_record/connection_adapters/abstract_adapter.rb:579:in `block (2 levels) in log'
/usr/local/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
/usr/local/bundle/gems/activerecord-5.2.0.rc1/lib/active_record/connection_adapters/abstract_adapter.rb:578:in `block in log'
/usr/local/bundle/gems/activesupport-5.2.0.rc1/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
/usr/local/bundle/gems/appsignal-2.4.3/lib/appsignal/hooks/active_support_notifications.rb:36:in `instrument'
/usr/local/bundle/gems/activerecord-5.2.0.rc1/lib/active_record/connection_adapters/abstract_adapter.rb:569:in `log'
/usr/local/bundle/gems/activerecord-5.2.0.rc1/lib/active_record/connection_adapters/postgresql/database_statements.rb:61:in `query'
/usr/local/bundle/gems/activerecord-5.2.0.rc1/lib/active_record/connection_adapters/abstract/database_statements.rb:89:in `query_values'
/usr/local/bundle/gems/activerecord-5.2.0.rc1/lib/active_record/connection_adapters/abstract/schema_statements.rb:36:in `data_sources'
/usr/local/bundle/gems/activerecord-5.2.0.rc1/lib/active_record/connection_adapters/schema_cache.rb:114:in `prepare_data_sources'
/usr/local/bundle/gems/activerecord-5.2.0.rc1/lib/active_record/connection_adapters/schema_cache.rb:48:in `data_source_exists?'
/usr/local/bundle/gems/activerecord-5.2.0.rc1/lib/active_record/model_schema.rb:324:in `table_exists?'
/usr/local/bundle/gems/activerecord-5.2.0.rc1/lib/active_record/attribute_methods/primary_key.rb:99:in `get_primary_key'
/usr/local/bundle/gems/activerecord-5.2.0.rc1/lib/active_record/attribute_methods/primary_key.rb:87:in `reset_primary_key'
/usr/local/bundle/gems/activerecord-5.2.0.rc1/lib/active_record/attribute_methods/primary_key.rb:75:in `primary_key'
/usr/local/bundle/gems/activerecord-5.2.0.rc1/lib/active_record/relation/delegation.rb:46:in `primary_key'
/usr/local/bundle/gems/activerecord-5.2.0.rc1/lib/active_record/relation.rb:323:in `update_all'
/usr/local/bundle/gems/newrelic_rpm-4.8.0.341/lib/new_relic/agent/instrumentation/active_record_prepend.rb:30:in `block in update_all'
/usr/local/bundle/gems/newrelic_rpm-4.8.0.341/lib/new_relic/agent.rb:620:in `with_database_metric_name'
/usr/local/bundle/gems/newrelic_rpm-4.8.0.341/lib/new_relic/agent/instrumentation/active_record_prepend.rb:29:in `update_all'
/usr/local/bundle/gems/delayed_job_active_record-4.1.2/lib/delayed/backend/active_record.rb:61:in `clear_locks!'
/usr/local/bundle/gems/delayed_job-4.1.4/lib/delayed/plugins/clear_locks.rb:9:in `ensure in block (2 levels) in <class:ClearLocks>'
/usr/local/bundle/gems/delayed_job-4.1.4/lib/delayed/plugins/clear_locks.rb:9:in `block (2 levels) in <class:ClearLocks>'
/usr/local/bundle/gems/delayed_job-4.1.4/lib/delayed/lifecycle.rb:79:in `block (2 levels) in add'
/usr/local/bundle/gems/delayed_job-4.1.4/lib/delayed/lifecycle.rb:61:in `block in initialize'
/usr/local/bundle/gems/delayed_job-4.1.4/lib/delayed/lifecycle.rb:79:in `block in add'
/usr/local/bundle/gems/delayed_job-4.1.4/lib/delayed/lifecycle.rb:66:in `execute'
/usr/local/bundle/gems/delayed_job-4.1.4/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/usr/local/bundle/gems/delayed_job-4.1.4/lib/delayed/worker.rb:171:in `start'
/usr/local/bundle/gems/delayed_job-4.1.4/lib/delayed/command.rb:137:in `run'
/usr/local/bundle/gems/delayed_job-4.1.4/lib/delayed/command.rb:125:in `block in run_process'
/usr/local/bundle/gems/daemons-1.2.6/lib/daemons/application.rb:270:in `block in start_proc'
/usr/local/bundle/gems/daemons-1.2.6/lib/daemons/application.rb:279:in `start_proc'
/usr/local/bundle/gems/daemons-1.2.6/lib/daemons/application.rb:300:in `start'
/usr/local/bundle/gems/daemons-1.2.6/lib/daemons/controller.rb:59:in `run'
/usr/local/bundle/gems/daemons-1.2.6/lib/daemons.rb:197:in `block in run_proc'
/usr/local/bundle/gems/daemons-1.2.6/lib/daemons/cmdline.rb:92:in `catch_exceptions'
/usr/local/bundle/gems/daemons-1.2.6/lib/daemons.rb:196:in `run_proc'
/usr/local/bundle/gems/delayed_job-4.1.4/lib/delayed/command.rb:123:in `run_process'
/usr/local/bundle/gems/delayed_job-4.1.4/lib/delayed/command.rb:104:in `block in daemonize'
/usr/local/bundle/gems/delayed_job-4.1.4/lib/delayed/command.rb:102:in `times'
/usr/local/bundle/gems/delayed_job-4.1.4/lib/delayed/command.rb:102:in `daemonize'
bin/delayed_job:5:in `<main>'
F, [2018-05-29T09:13:18.933436 #1] FATAL -- : PG::ConnectionBad: PQconsumeInput() could not receive data from server: Socket operation on non-socket
: SELECT c.relname FROM pg_class c LEFT JOIN pg_namespace n ON n.oid = c.relnamespace WHERE n.nspname = ANY (current_schemas(false)) AND c.relkind IN ('r','v','m','f')
2018-05-29T09:13:30+0000: [Worker(delayed_job host:2021426028b3 pid:1)] Starting job worker
D, [2018-05-29T09:14:30.818890 #1] DEBUG -- :  (0.5ms) SELECT COUNT(*) FROM "delayed_jobs" WHERE (failed_at is not NULL)
D, [2018-05-29T09:14:30.819676 #1] DEBUG -- :  (0.3ms) SELECT COUNT(*) FROM "delayed_jobs" WHERE (locked_by is not NULL)

//...............................
```

**Comment by albus522** [comment]
Closing stale
