### ISSUE TITLE
delayed job `require': no such file to load -- delayed/backend/active_record (LoadError)

### ISSUE THREAD

**Issue by tamoyal** [collectiveidea/delayed_job#314]
```
~/Projects/fsg_distro [with-ident] $ script/delayed_job start
/Library/Ruby/Gems/1.8/gems/activesupport-3.1.3/lib/active_support/dependencies.rb:240:in `require': no such file to load -- delayed/backend/active_record (LoadError)
    from /Library/Ruby/Gems/1.8/gems/activesupport-3.1.3/lib/active_support/dependencies.rb:240:in `require'
    from /Library/Ruby/Gems/1.8/gems/activesupport-3.1.3/lib/active_support/dependencies.rb:225:in `load_dependency'
    from /Library/Ruby/Gems/1.8/gems/activesupport-3.1.3/lib/active_support/dependencies.rb:240:in `require'
    from /Library/Ruby/Gems/1.8/bundler/gems/delayed_job-0c6c564c65f4/lib/delayed/worker.rb:41:in `backend='
    from /Users/tamoyal/Projects/fsg_distro/config/initializers/delayed_job_config.rb:8
    from /Library/Ruby/Gems/1.8/gems/activesupport-3.1.3/lib/active_support/dependencies.rb:234:in `load'
    from /Library/Ruby/Gems/1.8/gems/activesupport-3.1.3/lib/active_support/dependencies.rb:234:in `load'
    from /Library/Ruby/Gems/1.8/gems/activesupport-3.1.3/lib/active_support/dependencies.rb:225:in `load_dependency'
    from /Library/Ruby/Gems/1.8/gems/activesupport-3.1.3/lib/active_support/dependencies.rb:234:in `load'
    from /Library/Ruby/Gems/1.8/gems/railties-3.1.3/lib/rails/engine.rb:556
    from /Library/Ruby/Gems/1.8/gems/railties-3.1.3/lib/rails/engine.rb:555:in `each'
    from /Library/Ruby/Gems/1.8/gems/railties-3.1.3/lib/rails/engine.rb:555
    from /Library/Ruby/Gems/1.8/gems/railties-3.1.3/lib/rails/initializable.rb:30:in `instance_exec'
    from /Library/Ruby/Gems/1.8/gems/railties-3.1.3/lib/rails/initializable.rb:30:in `run'
    from /Library/Ruby/Gems/1.8/gems/railties-3.1.3/lib/rails/initializable.rb:55:in `run_initializers'
    from /Library/Ruby/Gems/1.8/gems/railties-3.1.3/lib/rails/initializable.rb:54:in `each'
    from /Library/Ruby/Gems/1.8/gems/railties-3.1.3/lib/rails/initializable.rb:54:in `run_initializers'
    from /Library/Ruby/Gems/1.8/gems/railties-3.1.3/lib/rails/application.rb:96:in `initialize!'
    from /Library/Ruby/Gems/1.8/gems/railties-3.1.3/lib/rails/railtie/configurable.rb:30:in `send'
    from /Library/Ruby/Gems/1.8/gems/railties-3.1.3/lib/rails/railtie/configurable.rb:30:in `method_missing'
    from ./script/../config/environment.rb:5
    from script/delayed_job:3:in `require'
    from script/delayed_job:3
```

In my gem file:
`gem 'delayed_job', '>= 2.1.2', :git => 'http://github.com/collectiveidea/delayed_job.git'`

I'm riding rails 3.1.3

**Comment by andrewpcone** [comment]
Thanks, belatedly!
