### ISSUE TITLE
Calling delay on an ActiveRecord object not in scope crashes

### ISSUE THREAD

**Issue by hult** [collectiveidea/delayed_job#805]
I have an active record model class with a default scope

    class MyModel < ActiveRecord::Base
      default_scope { where deleted_at: nil }
      def do_someting; puts deleted_at; end
    end

If I delay a job on an instance of this model not in scope

    MyModel.create!(deleted_at: Time.now).delay.do_something

then the entire worker process crashes

    ActiveRecord::RecordNotFound: Couldn't find MyModel with 'id'=1 [WHERE "my_models"."deleted_at" IS NULL]

```
08:55:17 worker.1 | /Users/magnus/.rvm/gems/ruby-2.1.3/gems/activerecord-4.1.6/lib/active_record/relation/finder_methods.rb:320:in `raise_record_not_found_exception!'
08:55:17 worker.1 | /Users/magnus/.rvm/gems/ruby-2.1.3/gems/activerecord-4.1.6/lib/active_record/relation/finder_methods.rb:429:in `find_one'
08:55:17 worker.1 | /Users/magnus/.rvm/gems/ruby-2.1.3/gems/activerecord-4.1.6/lib/active_record/relation/finder_methods.rb:413:in `find_with_ids'
08:55:17 worker.1 | /Users/magnus/.rvm/gems/ruby-2.1.3/gems/activerecord-4.1.6/lib/active_record/relation/finder_methods.rb:68:in `find'
08:55:17 worker.1 | /Users/magnus/.rvm/gems/ruby-2.1.3/gems/activerecord-4.1.6/lib/active_record/querying.rb:3:in `find'
08:55:17 worker.1 | /Users/magnus/.rvm/gems/ruby-2.1.3/bundler/gems/delayed_job-ce8869342918/lib/delayed/psych_ext.rb:40:in `visit_Psych_Nodes_Mapping'
08:55:17 worker.1 | /Users/magnus/.rvm/gems/ruby-2.1.3/bundler/gems/delayed_job-ce8869342918/lib/delayed/psych_ext.rb:35:in `visit_Psych_Nodes_Mapping'
08:55:17 worker.1 | /Users/magnus/.rvm/gems/ruby-2.1.3/bundler/gems/delayed_job-ce8869342918/lib/delayed/psych_ext.rb:17:in `load_dj'
08:55:17 worker.1 | /Users/magnus/.rvm/gems/ruby-2.1.3/bundler/gems/delayed_job-ce8869342918/lib/delayed/backend/base.rb:91:in `payload_object'
08:55:17 worker.1 | /Users/magnus/.rvm/gems/ruby-2.1.3/bundler/gems/delayed_job-ce8869342918/lib/delayed/backend/base.rb:138:in `max_run_time'
08:55:17 worker.1 | /Users/magnus/.rvm/gems/ruby-2.1.3/bundler/gems/delayed_job-ce8869342918/lib/delayed/worker.rb:284:in `max_run_time'
08:55:17 worker.1 | /Users/magnus/.rvm/gems/ruby-2.1.3/bundler/gems/delayed_job-ce8869342918/lib/delayed/worker.rb:223:in `block in run'
08:55:17 worker.1 | /Users/magnus/.rvm/gems/ruby-2.1.3/bundler/gems/delayed_job-ce8869342918/lib/delayed/worker.rb:222:in `run'
08:55:17 worker.1 | /Users/magnus/.rvm/gems/ruby-2.1.3/bundler/gems/delayed_job-ce8869342918/lib/delayed/worker.rb:299:in `block in reserve_and_run_one_job'
08:55:17 worker.1 | /Users/magnus/.rvm/gems/ruby-2.1.3/bundler/gems/delayed_job-ce8869342918/lib/delayed/lifecycle.rb:61:in `call'
08:55:17 worker.1 | /Users/magnus/.rvm/gems/ruby-2.1.3/bundler/gems/delayed_job-ce8869342918/lib/delayed/lifecycle.rb:61:in `block in initialize'
08:55:17 worker.1 | /Users/magnus/.rvm/gems/ruby-2.1.3/bundler/gems/delayed_job-ce8869342918/lib/delayed/lifecycle.rb:66:in `call'
08:55:17 worker.1 | /Users/magnus/.rvm/gems/ruby-2.1.3/bundler/gems/delayed_job-ce8869342918/lib/delayed/lifecycle.rb:66:in `execute'
08:55:17 worker.1 | /Users/magnus/.rvm/gems/ruby-2.1.3/bundler/gems/delayed_job-ce8869342918/lib/delayed/lifecycle.rb:40:in `run_callbacks'
08:55:17 worker.1 | /Users/magnus/.rvm/gems/ruby-2.1.3/bundler/gems/delayed_job-ce8869342918/lib/delayed/worker.rb:299:in `reserve_and_run_one_job'
08:55:17 worker.1 | /Users/magnus/.rvm/gems/ruby-2.1.3/bundler/gems/delayed_job-ce8869342918/lib/delayed/worker.rb:206:in `block in work_off'
08:55:17 worker.1 | /Users/magnus/.rvm/gems/ruby-2.1.3/bundler/gems/delayed_job-ce8869342918/lib/delayed/worker.rb:205:in `times'
08:55:17 worker.1 | /Users/magnus/.rvm/gems/ruby-2.1.3/bundler/gems/delayed_job-ce8869342918/lib/delayed/worker.rb:205:in `work_off'
08:55:17 worker.1 | /Users/magnus/.rvm/gems/ruby-2.1.3/bundler/gems/delayed_job-ce8869342918/lib/delayed/worker.rb:169:in `block (4 levels) in start'
08:55:17 worker.1 | /Users/magnus/.rvm/gems/ruby-2.1.3/bundler/gems/delayed_job-ce8869342918/lib/delayed/worker.rb:168:in `block (3 levels) in start'
08:55:17 worker.1 | /Users/magnus/.rvm/gems/ruby-2.1.3/bundler/gems/delayed_job-ce8869342918/lib/delayed/lifecycle.rb:61:in `call'
08:55:17 worker.1 | /Users/magnus/.rvm/gems/ruby-2.1.3/bundler/gems/delayed_job-ce8869342918/lib/delayed/lifecycle.rb:61:in `block in initialize'
08:55:17 worker.1 | /Users/magnus/.rvm/gems/ruby-2.1.3/bundler/gems/delayed_job-ce8869342918/lib/delayed/lifecycle.rb:66:in `call'
08:55:17 worker.1 | /Users/magnus/.rvm/gems/ruby-2.1.3/bundler/gems/delayed_job-ce8869342918/lib/delayed/lifecycle.rb:66:in `execute'
08:55:17 worker.1 | /Users/magnus/.rvm/gems/ruby-2.1.3/bundler/gems/delayed_job-ce8869342918/lib/delayed/lifecycle.rb:40:in `run_callbacks'
08:55:17 worker.1 | /Users/magnus/.rvm/gems/ruby-2.1.3/bundler/gems/delayed_job-ce8869342918/lib/delayed/worker.rb:167:in `block (2 levels) in start'
08:55:17 worker.1 | /Users/magnus/.rvm/gems/ruby-2.1.3/bundler/gems/delayed_job-ce8869342918/lib/delayed/worker.rb:166:in `loop'
08:55:17 worker.1 | /Users/magnus/.rvm/gems/ruby-2.1.3/bundler/gems/delayed_job-ce8869342918/lib/delayed/worker.rb:166:in `block in start'
08:55:17 worker.1 | /Users/magnus/.rvm/gems/ruby-2.1.3/bundler/gems/delayed_job-ce8869342918/lib/delayed/plugins/clear_locks.rb:7:in `call'
08:55:17 worker.1 | /Users/magnus/.rvm/gems/ruby-2.1.3/bundler/gems/delayed_job-ce8869342918/lib/delayed/plugins/clear_locks.rb:7:in `block (2 levels) in <class:ClearLocks>'
08:55:17 worker.1 | /Users/magnus/.rvm/gems/ruby-2.1.3/bundler/gems/delayed_job-ce8869342918/lib/delayed/lifecycle.rb:79:in `call'
08:55:17 worker.1 | /Users/magnus/.rvm/gems/ruby-2.1.3/bundler/gems/delayed_job-ce8869342918/lib/delayed/lifecycle.rb:79:in `block (2 levels) in add'
08:55:17 worker.1 | /Users/magnus/.rvm/gems/ruby-2.1.3/bundler/gems/delayed_job-ce8869342918/lib/delayed/lifecycle.rb:61:in `call'
08:55:17 worker.1 | /Users/magnus/.rvm/gems/ruby-2.1.3/bundler/gems/delayed_job-ce8869342918/lib/delayed/lifecycle.rb:61:in `block in initialize'
08:55:17 worker.1 | /Users/magnus/.rvm/gems/ruby-2.1.3/bundler/gems/delayed_job-ce8869342918/lib/delayed/lifecycle.rb:79:in `call'
08:55:17 worker.1 | /Users/magnus/.rvm/gems/ruby-2.1.3/bundler/gems/delayed_job-ce8869342918/lib/delayed/lifecycle.rb:79:in `block in add'
08:55:17 worker.1 | /Users/magnus/.rvm/gems/ruby-2.1.3/bundler/gems/delayed_job-ce8869342918/lib/delayed/lifecycle.rb:66:in `call'
08:55:17 worker.1 | /Users/magnus/.rvm/gems/ruby-2.1.3/bundler/gems/delayed_job-ce8869342918/lib/delayed/lifecycle.rb:66:in `execute'
08:55:17 worker.1 | /Users/magnus/.rvm/gems/ruby-2.1.3/bundler/gems/delayed_job-ce8869342918/lib/delayed/lifecycle.rb:40:in `run_callbacks'
08:55:17 worker.1 | /Users/magnus/.rvm/gems/ruby-2.1.3/bundler/gems/delayed_job-ce8869342918/lib/delayed/worker.rb:165:in `start'
08:55:17 worker.1 | /Users/magnus/.rvm/gems/ruby-2.1.3/bundler/gems/delayed_job-ce8869342918/lib/delayed/tasks.rb:9:in `block (2 levels) in <top (required)>'
08:55:17 worker.1 | /Users/magnus/.rvm/gems/ruby-2.1.3/bin/ruby_executable_hooks:15:in `eval'
08:55:17 worker.1 | /Users/magnus/.rvm/gems/ruby-2.1.3/bin/ruby_executable_hooks:15:in `<main>'
08:55:17 worker.1 | Tasks: TOP => jobs:work
08:55:17 worker.1 | (See full trace by running task with --trace)
08:55:17 worker.1 | exited with code 1
08:55:17 system   | sending SIGTERM to all processes
```

**Comment by albus522** [comment]
You have something else going on as https://github.com/collectiveidea/delayed_job/blob/master/lib/delayed/psych_ext.rb#L41 rescues the RecordNotFound error. My guess is that it has something to do with the SIGTERM thrown in the middle of that statement as I have no idea where that is coming from.

Either way, DJ does not currently support delaying something that does not fall in your default scope. This is a design decision and is not likely to change. If you need to override this behavior you can create a class method that you call with the record id as an argument that calls the appropriate finder.

```
class MyModel < ActiveRecord::Base
  default_scope { where deleted_at: nil }

  def self.do_something_later(id)
    unscoped.find(id).do_something
  end

  def do_someting
    puts deleted_at
  end
end

MyModel.delay.do_something_later(MyModel.create!(deleted_at: Time.now).id)
```

**Comment by hult** [comment]
Fair enough. I do think it's a weird timing introducing this pretty large incompatibility between versions 4.0.3 and 4.0.4 though. I guess we'll have to not upgrade for now.

**Comment by albus522** [comment]
So in looking over the history on this one. It looks like as we stopped rejiggering YAML we introduced a couple of small behavioral changes in trying to interfere less in default behaviors.

I think some of the new behavior change, came from looking at how ActiveJob and the new GlobalID stuff works. The new behavior is very similar to how GlobalID works now.
