### ISSUE TITLE
#deliver_later not working with DJ 4.1.3/Ruby 2.4.0/Rails 5.1.1 when using delayed_job as adapter

### ISSUE THREAD

**Issue by thenadz** [collectiveidea/delayed_job#983]
Using ActiveMailer, delivering synchronously works without issue, but running through the delayed_job adapter I get the following error. Of course, `default_url_options[:host]` is being initialized in application.rb (otherwise the plain `#deliver` call would not work).

I'm assuming I'm doing something dumb, but after quite a bit of googling around, I've yet to figure out what that dumb thing is.

application.rb
```
config.action_mailer.default_url_options = { host: ENV['HOSTNAME'] }
```

error + stacktrace
```
ERROR -- : [ActiveJob] [ActionMailer::DeliveryJob] [9ea66c90-6de0-4ae8-a323-b185a05e7889] Error performing ActionMai
ler::DeliveryJob (Job ID: 9ea66c90-6de0-4ae8-a323-b185a05e7889) from DelayedJob(production.mailers) in 1.85ms: ActionView::Template::Error (Missing host to
 link to! Please provide the :host parameter, set default_url_options[:host], or set :only_path to true):
/home/rails/.rvm/gems/ruby-2.4.0/gems/actionpack-5.1.1/lib/action_dispatch/http/url.rb:62:in `full_url_for'
/home/rails/.rvm/gems/ruby-2.4.0/gems/actionpack-5.1.1/lib/action_dispatch/http/url.rb:52:in `url_for'
/home/rails/.rvm/gems/ruby-2.4.0/gems/actionpack-5.1.1/lib/action_dispatch/routing/route_set.rb:331:in `block in <class:RouteSet>'
/home/rails/.rvm/gems/ruby-2.4.0/gems/actionpack-5.1.1/lib/action_dispatch/routing/route_set.rb:826:in `url_for'
/home/rails/.rvm/gems/ruby-2.4.0/gems/actionpack-5.1.1/lib/action_dispatch/routing/route_set.rb:267:in `call'
/home/rails/.rvm/gems/ruby-2.4.0/gems/actionpack-5.1.1/lib/action_dispatch/routing/route_set.rb:208:in `call'
/home/rails/.rvm/gems/ruby-2.4.0/gems/actionpack-5.1.1/lib/action_dispatch/routing/route_set.rb:323:in `block (2 levels) in define_url_helper'
/home/rails/thumber_co/app/views/user_mailer/welcome.html.erb:14:in `_app_views_user_mailer_welcome_html_erb__2119493127553626931_43639480'
/home/rails/.rvm/gems/ruby-2.4.0/gems/actionview-5.1.1/lib/action_view/template.rb:157:in `block in render'
/home/rails/.rvm/gems/ruby-2.4.0/gems/activesupport-5.1.1/lib/active_support/notifications.rb:168:in `instrument'
/home/rails/.rvm/gems/ruby-2.4.0/gems/actionview-5.1.1/lib/action_view/template.rb:352:in `instrument_render_template'
/home/rails/.rvm/gems/ruby-2.4.0/gems/actionview-5.1.1/lib/action_view/template.rb:155:in `render'
/home/rails/.rvm/gems/ruby-2.4.0/gems/actionview-5.1.1/lib/action_view/renderer/template_renderer.rb:52:in `block (2 levels) in render_template'
/home/rails/.rvm/gems/ruby-2.4.0/gems/actionview-5.1.1/lib/action_view/renderer/abstract_renderer.rb:42:in `block in instrument'
/home/rails/.rvm/gems/ruby-2.4.0/gems/activesupport-5.1.1/lib/active_support/notifications.rb:166:in `block in instrument'
/home/rails/.rvm/gems/ruby-2.4.0/gems/activesupport-5.1.1/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
/home/rails/.rvm/gems/ruby-2.4.0/gems/activesupport-5.1.1/lib/active_support/notifications.rb:166:in `instrument'
/home/rails/.rvm/gems/ruby-2.4.0/gems/actionview-5.1.1/lib/action_view/renderer/abstract_renderer.rb:41:in `instrument'
/home/rails/.rvm/gems/ruby-2.4.0/gems/actionview-5.1.1/lib/action_view/renderer/template_renderer.rb:51:in `block in render_template'
/home/rails/.rvm/gems/ruby-2.4.0/gems/actionview-5.1.1/lib/action_view/renderer/template_renderer.rb:59:in `render_with_layout'
/home/rails/.rvm/gems/ruby-2.4.0/gems/actionview-5.1.1/lib/action_view/renderer/template_renderer.rb:50:in `render_template'
/home/rails/.rvm/gems/ruby-2.4.0/gems/actionview-5.1.1/lib/action_view/renderer/template_renderer.rb:14:in `render'
/home/rails/.rvm/gems/ruby-2.4.0/gems/actionview-5.1.1/lib/action_view/renderer/renderer.rb:42:in `render_template'
/home/rails/.rvm/gems/ruby-2.4.0/gems/actionview-5.1.1/lib/action_view/renderer/renderer.rb:23:in `render'
/home/rails/.rvm/gems/ruby-2.4.0/gems/actionview-5.1.1/lib/action_view/rendering.rb:103:in `_render_template'
/home/rails/.rvm/gems/ruby-2.4.0/gems/actionview-5.1.1/lib/action_view/rendering.rb:83:in `render_to_body'
/home/rails/.rvm/gems/ruby-2.4.0/gems/actionpack-5.1.1/lib/abstract_controller/rendering.rb:24:in `render'
/home/rails/.rvm/gems/ruby-2.4.0/gems/actionmailer-5.1.1/lib/action_mailer/base.rb:935:in `block in collect_responses_from_templates'
/home/rails/.rvm/gems/ruby-2.4.0/gems/actionmailer-5.1.1/lib/action_mailer/base.rb:932:in `each'
/home/rails/.rvm/gems/ruby-2.4.0/gems/actionmailer-5.1.1/lib/action_mailer/base.rb:932:in `each'
/home/rails/.rvm/gems/ruby-2.4.0/gems/actionmailer-5.1.1/lib/action_mailer/base.rb:932:in `map'
/home/rails/.rvm/gems/ruby-2.4.0/gems/actionmailer-5.1.1/lib/action_mailer/base.rb:932:in `collect_responses_from_templates'
/home/rails/.rvm/gems/ruby-2.4.0/gems/actionmailer-5.1.1/lib/action_mailer/base.rb:917:in `collect_responses'
/home/rails/.rvm/gems/ruby-2.4.0/gems/actionmailer-5.1.1/lib/action_mailer/base.rb:830:in `mail'
/home/rails/thumber_co/app/mailers/user_mailer.rb:5:in `welcome'
/home/rails/.rvm/gems/ruby-2.4.0/gems/actionpack-5.1.1/lib/abstract_controller/base.rb:186:in `process_action'
/home/rails/.rvm/gems/ruby-2.4.0/gems/actionpack-5.1.1/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
/home/rails/.rvm/gems/ruby-2.4.0/gems/activesupport-5.1.1/lib/active_support/callbacks.rb:97:in `run_callbacks'
/home/rails/.rvm/gems/ruby-2.4.0/gems/actionpack-5.1.1/lib/abstract_controller/callbacks.rb:19:in `process_action'
/home/rails/.rvm/gems/ruby-2.4.0/gems/actionpack-5.1.1/lib/abstract_controller/base.rb:124:in `process'
/home/rails/.rvm/gems/ruby-2.4.0/gems/actionmailer-5.1.1/lib/action_mailer/rescuable.rb:23:in `block in process'
/home/rails/.rvm/gems/ruby-2.4.0/gems/actionmailer-5.1.1/lib/action_mailer/rescuable.rb:15:in `handle_exceptions'
/home/rails/.rvm/gems/ruby-2.4.0/gems/actionmailer-5.1.1/lib/action_mailer/rescuable.rb:22:in `process'
/home/rails/.rvm/gems/ruby-2.4.0/gems/actionview-5.1.1/lib/action_view/rendering.rb:30:in `process'
/home/rails/.rvm/gems/ruby-2.4.0/gems/actionmailer-5.1.1/lib/action_mailer/base.rb:609:in `block in process'
/home/rails/.rvm/gems/ruby-2.4.0/gems/activesupport-5.1.1/lib/active_support/notifications.rb:166:in `block in instrument'
/home/rails/.rvm/gems/ruby-2.4.0/gems/activesupport-5.1.1/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
/home/rails/.rvm/gems/ruby-2.4.0/gems/activesupport-5.1.1/lib/active_support/notifications.rb:166:in `instrument'
/home/rails/.rvm/gems/ruby-2.4.0/gems/actionmailer-5.1.1/lib/action_mailer/base.rb:608:in `process'
/home/rails/.rvm/gems/ruby-2.4.0/gems/actionmailer-5.1.1/lib/action_mailer/message_delivery.rb:105:in `block in processed_mailer'
/home/rails/.rvm/gems/ruby-2.4.0/gems/actionmailer-5.1.1/lib/action_mailer/message_delivery.rb:104:in `tap'
/home/rails/.rvm/gems/ruby-2.4.0/gems/actionmailer-5.1.1/lib/action_mailer/message_delivery.rb:104:in `processed_mailer'
/home/rails/.rvm/gems/ruby-2.4.0/gems/actionmailer-5.1.1/lib/action_mailer/message_delivery.rb:95:in `deliver_now'
```

**Comment by albus522** [comment]
My guess is that environment variable is not set when and where the DJ process is started.

**Comment by thenadz** [comment]
@albus522 That was my first thought, but the value is initialized in application.rb, so env doesn't come into play. Also, the logs indicate that DJ is running in production env.

**Comment by albus522** [comment]
`ENV['HOSTNAME']` is a command line environment variable. That has to be set outside the process for the process to pick it up.

**Comment by thenadz** [comment]
@albus522 Ah. I see what you're asking. No, it's not that. Replacing with a hard-coded string does the same thing.

**Comment by albus522** [comment]
The workers do not pickup code changes automatically. You have a worker process started that was incorrectly started and has not quit as expected. Do a full stop of all DJ workers. Confirm that every worker process has exited. Then start up fresh. There is nothing special about DJs boot process. DJ simply runs the standard rails boot process same as every other rails process.

**Comment by ChunAllen** [comment]
I'm also encountering this issue, I'm using capistrano 3 and Delayed Job. I'm getting 
```
Missing template admin/reminder with "mailer". 
```
I'm using a `deliver_now` method to send the email. 

Whenever I deploy I stop and run again the delayed job here's the code snippet: 
```
namespace :delayed_job do

  def args
    fetch(:delayed_job_args, "")
  end

  def delayed_job_roles
    fetch(:delayed_job_server_role, :app)
  end

  desc 'Stop the delayed_job process'
  task :stop do
    on roles(delayed_job_roles) do
      within release_path do
        with rails_env: fetch(:rails_env) do
          execute :bundle, :exec, :'bin/delayed_job', :stop
        end
      end
    end
  end

  desc 'Start the delayed_job process'
  task :start do
    on roles(delayed_job_roles) do
      within release_path do
        with rails_env: fetch(:rails_env) do
          execute :bundle, :exec, :'bin/delayed_job', args, :start
        end
      end
    end
  end

end
```

and 
```
after 'deploy:published', 'delayed_job:stop'
after 'deploy:published', 'delayed_job:start'
```

I'm thinking that it's not fully stopping the delayed job worker. How can I stop all DJ process and start a fresh process?

**Comment by albus522** [comment]
@ChunAllen `deliver_now` doesn't use DJ or any background processor for that matter. If you mean you are calling `deliver_now` within a job, all I can tell you is to watch for orphaned processes. We rely on the daemons gem and historically it has a lot of edge cases which can cause weird behaviors. The daemons gem covers a lot of stuff we don't want to deal with but it isn't perfect.
