### ISSUE TITLE
I can't use delayed_job because of ActiveRecord::StatementInvalid: SQLite3::SQLException: cannot rollback - no transaction is active: rollback transaction  

### ISSUE THREAD

**Issue by NishidaRyu416** [collectiveidea/delayed_job#989]
[![Screenshot from Gyazo](https://gyazo.com/9ccc77c39e352b9d44e284b2f1ee4d6c/raw)](https://gyazo.com/9ccc77c39e352b9d44e284b2f1ee4d6c)
```
#controllerr

  def quizlet
    @response=[]
    response = Unirest.get "https://api.quizlet.com/2.0/search/sets/?client_id=7JH38T27zM&whitespace=1",
                           parameters:{ whitespace: true,q: "Duo3.0",term:100,sort:"most_studied"}
    res=response.body

    quizlet_ids=[]
    res["sets"].each do|res|
      quizlet_ids<<res["id"]
    end


    quizlet_words = Unirest.get "https://api.quizlet.com/2.0/sets/?client_id=7JH38T27zM&whitespace=1",
                                parameters:{ whitespace: true,set_ids:"#{quizlet_ids}"}

    quizlet_words.body.each do|words|
      words["terms"].each do|word|
        response=word
        response["quizlet_id"]=words["id"]
        response["check_id"]=word["id"]
        response["question_language"]= words["lang_terms"]
        response["answer_language"]  = words["lang_definitions"]
        @response<<response
        @response.each do|response|
          Word.delay.quizlet_save(response["quizlet_id"],response["check_id"],response["term"],response["definition"],response["question_language"],response["answer_language"])
        end
      end
    end
  end
```

```
#model

def quizlet_save(quizlet_id,check_id,question,answer,question_language,answer_language)
    unless Word.find_by(check_id:check_id)&&Word.find_by(quizlet_id:quizlet_id)
      Word.create(quizlet_id:quizlet_id,check_id:check_id,title:"Quizlet",question:question,answer:answer,user_id:1,tag_list:"English,duo3.0,Vocabulary",
                  question_language:question_language,answer_language:answer_language)
    end
    word=Word.find_by(check_id:check_id)
    unless word == nil
      checking_word=Word.find_by(quizlet_id:quizlet_id)
      group=Group.find_by(id: checking_word.group_id)
      if group==nil
        created_group=Group.new(user_id:1,title:"Quizlet",explanation:"Quizlet Duo3.0")
        created_group=created_group.save(validate: false)&&created_group
        word.update_attribute(:group_id,created_group.id)
      else
        word.update_attribute(:group_id,group.id)
      end
    end
  end
```
Can anybody tell me the solution?

**Comment by albus522** [comment]
SQLite is a single process database, meaning only one process can access the database at a time, so it does not work with DJ or any other background processor that runs in a separate process. The only option I know of that MIGHT work for you is https://rubygems.org/gems/sucker_punch

**Comment by NishidaRyu416** [comment]
Thank you for answering. I could understand and thanks to you I used `sucker_punch` in my development environment but it didn't helpful in heroku that uses progresql so such a problem will never happen .So I wanna use `delayed_job` but an error happened that is below.

```
 ArgumentError (job cannot be created for non-persisted record: #<Word id: nil, group_id: nil, user_id: nil, answer: nil, question: nil, title: nil, image: nil, created_at: nil, updated_at: nil, answer_language: nil, question_language: nil, favorites_count: 0, quizlet_id: nil, check_id: nil>):
2017-07-12T09:45:33.457139+00:00 app[web.1]:   app/controllers/words_controller.rb:209:in `block (3 levels) in quizlet'
2017-07-12T09:45:33.457141+00:00 app[web.1]:   app/controllers/words_controller.rb:208:in `each'
2017-07-12T09:45:33.457141+00:00 app[web.1]:   app/controllers/words_controller.rb:208:in `block (2 levels) in quizlet'
2017-07-12T09:45:33.457142+00:00 app[web.1]:   app/controllers/words_controller.rb:201:in `each'
2017-07-12T09:45:33.457143+00:00 app[web.1]:   app/controllers/words_controller.rb:201:in `block in quizlet'
2017-07-12T09:45:33.457143+00:00 app[web.1]:   app/controllers/words_controller.rb:200:in `each'
2017-07-12T09:45:33.457144+00:00 app[web.1]:   app/controllers/words_controller.rb:200:in `quizlet'
2017-07-12T09:45:33.457144+00:00 app[web.1]:   app/controllers/words_controller.rb:49:in `new'
```

**Comment by albus522** [comment]
As the error says DJ can't create jobs for or on non-persisted records. The record must be saved before it can be used in a job.

**Comment by NishidaRyu416** [comment]
Thanks I could fix.In spite of Asynchronous processing,It needs too much time to response so it doesn't use in Heroku. So I wanna  ask you,is that to blame for sever that is Heroku ?
